name: Dagster Prod Deploy
on:
  push:
    branches:
      - "main"
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_URL }}
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

jobs:
  load_build_info:
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.load-build-info.outputs.build_info }}
      secrets_set: ${{ steps.check-secrets.outputs.okay }}
    steps:
      - uses: actions/checkout@v2
      - name: Load build info
        id: load-build-info
        uses: dagster-io/cloud-branch-deployments-action/load_build_info@main
        with:
          dagster_cloud_file: cloud_workspace.yaml
      - name: check for secrets needed to deploy
        id: check-secrets
        run: |
          if [ ! -z "$DAGSTER_CLOUD_API_TOKEN" ]; then
            echo "::set-output name=okay::true"
          fi

  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    needs: load_build_info
    if: ${{ needs.load_build_info.outputs.secrets_set }}
    name: Dagster Serverless Deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.load_build_info.outputs.build_info) }}
    steps:
      - name: Get serverless organization info
        uses: dagster-io/dagster-cloud-serverless-action/registry_info@main
        with:
          organization_id: ${{ secrets.ORGANIZATION_ID }}
          deployment: prod
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Copy user code template file
        uses: dagster-io/dagster-cloud-serverless-action/copy_template@main
        with:
          target_directory: ${{ matrix.location.directory }}
          env_vars: ${{ toJson(secrets) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.location.directory }}
          push: true
          tags: "${{ env.REGISTRY_URL }}:${{ github.sha }}"
          labels: |
            branch=${{ github.head_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Dagster Cloud
        uses: dagster-io/cloud-branch-deployments-action/deploy@main
        id: deploy
        with:
          organization_id: ${{ secrets.ORGANIZATION_ID }}
          deployment: prod
          pr: "${{ github.event.number }}"
          location: ${{ toJson(matrix.location) }}
          image_tag: ${{ github.sha }}
          registry: ${{ env.REGISTRY_URL }}
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
